### ISSUE TITLE
Problems with ScrollSnapLoop

### ISSUE THREAD

**Issue by uncle-ara** [barthy-koeln/scroll-snap-slider#23] opened 2024-02-12 21:16 UTC
Hello.

Why can't ScrollSnapDraggable and ScrollSnapLoop work together?
Is it even possible to do it?

I read the description from the author. But I want to fix it

**Comment by barthy-koeln** [comment] 2024-02-13 08:03
Hi,

Thanks for your interest!

Honestly, I couldn't replicate the issues I was having with the combination. But I have also rewritten parts of both plugins since writing the initial documentation.

I will revisit this today. If you want to help, you could create a small example and test it yourself. Try to break it :)

Also, please note that the "ScrollSnapDraggable" plugin is only required for mouse dragging. The slider is natively draggable on touchscreens. 

Barthy

**Comment by barthy-koeln** [comment] 2024-02-13 08:23
Hey @uncle-ara 

Please check out the demo in the branch [fix/draggable_cancel_slide_stop_listener](https://github.com/barthy-koeln/scroll-snap-slider/tree/fix/draggable_cancel_slide_stop_listener). You can enable both plugins there.

Simply clone the project and run `yarn install` and `yarn watch`.

**Comment by uncle-ara** [comment] 2024-02-13 09:26
Hello :) @barthy-koeln 

I'll test and I'm on my way to you

**Comment by uncle-ara** [comment] 2024-02-13 09:50
@barthy-koeln 
Here's the video. I'm the one with the problem with ScrollSnapDraggable enabled

https://github.com/barthy-koeln/scroll-snap-slider/assets/47677284/d6dd4843-0389-4cde-b759-3c08e93b3ee8

**Comment by barthy-koeln** [comment] 2024-02-13 15:25
I meant `yarn dev` sorry.

Can you provide a reproducible example? Maybe using the [React Starter on Stackblitz](https://stackblitz.com/edit/react-starter). I can then help you debug it.

**Comment by uncle-ara** [comment] 2024-02-13 16:41
> I meant `yarn dev` sorry.
> 
> Can you provide a reproducible example? Maybe using the [React Starter on Stackblitz](https://stackblitz.com/edit/react-starter). I can then help you debug it.

[Stackblitz](https://stackblitz.com/edit/stackblitz-starters-hgpa4t?description=The%20React%20framework%20for%20production&file=components%2FSlider%2FSlider.tsx,components%2FSlider%2Ftypes.ts,components%2FCardSlider%2FCardSlider.tsx,app%2Fpage.tsx&title=Next.js%20Starter)

**Comment by barthy-koeln** [comment] 2024-02-13 18:55
Thanks, that helped a lot.

You're using `display: grid` with `gap: ${spaceBetween}px`.

This means that calculations are off by `spaceBetween` pixels every time you release the cursor.
To correct this, override the `sizingMethod`:

```ts
const slider = new ScrollSnapSlider({
  element,
  sizingMethod: (slider: ScrollSnapSlider) => {
    return (
      (slider.element.firstElementChild as HTMLElement).offsetWidth +
      spaceBetween
    );
  },
}).with([
  new ScrollSnapDraggable(),
]);
```

Note that this means the last slide is smaller than calculated, which in turn could cause issues with scroll-snap-loop.
I will investigate this and try to come up with another solution.

I will also properly document this in the README, it's currently only mentioned once in a code snippet.

Another improvement is #24 that you've already discovered. I will test this further and merge it this week.

**Comment by uncle-ara** [comment] 2024-02-13 19:09
> ```ts
> ScrollSnapDraggable
> ```

ScrollSnapDraggable - that makes sense to me, thank you very much! 
What about slider.slide which is undefined? I pointed that out there in [Stackblitz](https://stackblitz.com/edit/stackblitz-starters-hgpa4t?description=The%20React%20framework%20for%20production&file=components%2FSlider%2FSlider.tsx,components%2FSlider%2Ftypes.ts,components%2FCardSlider%2FCardSlider.tsx,app%2Fpage.tsx&title=Next.js%20Starter).

**Comment by uncle-ara** [comment] 2024-02-13 19:11
> Thanks, that helped a lot.
> 
> You're using `display: grid` with `gap: ${spaceBetween}px`.
> 
> This means that calculations are off by `spaceBetween` pixels every time you release the cursor. To correct this, override the `sizingMethod`:
> 
> ```ts
> const slider = new ScrollSnapSlider({
>   element,
>   sizingMethod: (slider: ScrollSnapSlider) => {
>     return (
>       (slider.element.firstElementChild as HTMLElement).offsetWidth +
>       spaceBetween
>     );
>   },
> }).with([
>   new ScrollSnapDraggable(),
> ]);
> ```
> 
> Note that this means the last slide is smaller than calculated, which in turn could cause issues with scroll-snap-loop. I will investigate this and try to come up with another solution.
> 
> I will also properly document this in the README, it's currently only mentioned once in a code snippet.
> 
> Another improvement is #24 that you've already discovered. I will test this further and merge it this week.

ScrollSnapDraggable - that makes sense to me, thank you very much! 
What about slider.slide which is undefined? I pointed that out there in [Stackblitz](https://stackblitz.com/edit/stackblitz-starters-hgpa4t?description=The%20React%20framework%20for%20production&file=components%2FSlider%2FSlider.tsx,components%2FSlider%2Ftypes.ts,components%2FCardSlider%2FCardSlider.tsx,app%2Fpage.tsx&title=Next.js%20Starter).

**Comment by barthy-koeln** [comment] 2024-02-16 13:39
> What about slider.slide which is undefined

The calculations are done in an animation frame callback. Meaning that in your example, `slider.slide` is undefined for a very short amount of time. 

I will also document this. I haven't come across a slider where I needed to know the calculated slide right away — they usually start at 0.

What's your precise use-case?

**Comment by uncle-ara** [comment] 2024-02-16 20:33
> > What about slider.slide which is undefined
> 
> The calculations are done in an animation frame callback. Meaning that in your example, `slider.slide` is undefined for a very short amount of time.
> 
> I will also document this. I haven't come across a slider where I needed to know the calculated slide right away — they usually start at 0.
> 
> What's your precise use-case?

I wanted to implement a function that locks the Prev and Next buttons if the slides are over, so I want to get the value of slider.slide

I have a callback function onBeforeInit, where I want to return the state of the buttons so that the parent component has that state.

Example:
disabledPrev: boolean
disabledNext: boolean

**Comment by barthy-koeln** [comment] 2024-02-20 23:17
I went back in and figured out the `requestAnimatonFrame` I mentioned was not necessary, potentially even detrimental to performance. I removed it in `main` and will soon publish a new release.

Can you try your project with my `main` branch?

**Comment by uncle-ara** [comment] 2024-02-21 11:13
> I went back in and figured out the `requestAnimatonFrame` I mentioned was not necessary, potentially even detrimental to performance. I removed it in `main` and will soon publish a new release.
> 
> Can you try your project with my `main` branch?

I'll try, I'll be back in a few hours with an answer.

**Comment by uncle-ara** [comment] 2024-02-22 21:35
> I went back in and figured out the `requestAnimatonFrame` I mentioned was not necessary, potentially even detrimental to performance. I removed it in `main` and will soon publish a new release.
> 
> Can you try your project with my `main` branch?

Let's just publish the new version with fixes and I'll check it on my working project.

**Comment by barthy-koeln** [comment] 2024-09-30 11:41
Closing, assuming things are fine or irrelevant now.

**Closed by barthy-koeln** 2024-09-30 11:41 UTC
Labels: enhancement
